baseURL: https://jjshaws.github.io/
languageCode: en-us
title: JamesShaw.info
theme: "PaperMod"
disableFastRender: true
googleAnalytics: "G-F3ZFR9P9GD"

#for papermod search
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    - identifier: Photography
      name: Photography
      url: /photography/
      weight: 1
    - identifier: Bookshelf
      name: Bookshelf
      url: /books/
      weight: 3
    - identifier: Posts
      name: Posts
      url: /posts/
      weight: 2
    - identifier: Search
      name: Search
      url: /search/
      weight: 4